### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [fvalverd/AutoApi#6]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 2.1.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary auto-api -w /tmp/ext auto-api==2.1.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting auto-api==2.1.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/710/fcc133846de1b/auto_api-2.1.0.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-b3_bg89z/auto-api/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-b3_bg89z/auto-api/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-b3_bg89z/auto-api/pip-egg-info
         cwd: /tmp/pip-wheel-b3_bg89z/auto-api/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-b3_bg89z/auto-api/setup.py", line 39, in <module>
        install_requires=read_requirements(REQUIREMENTS),
      File "/tmp/pip-wheel-b3_bg89z/auto-api/setup.py", line 31, in read_requirements
        with open(path) as file:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-b3_bg89z/auto-api/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
It appears this doesn't happen with current versions of setuptools/pip from the repo.

**Comment by fvalverd** [comment]
Exactly, the latest version fixes this.
